name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux
      options: --privileged

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pacman --noconfirm -Syu base-devel cmake libgit2 curl json-c

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cd ${{github.workspace}}/build && make
